name: Multi-Docker Build and Push
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Test Image
        run: docker build -t shaydeecoder/multi-react-test -f ./client/Dockerfile.dev ./client

      - name: Run Tests
        run: docker run -e CI=true shaydeecoder/multi-react-test npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images
        run: |
          docker build -t shaydeecoder/multi-client ./client
          docker build -t shaydeecoder/multi-nginx ./nginx
          docker build -t shaydeecoder/multi-server ./server
          docker build -t shaydeecoder/multi-worker ./worker

      - name: Push Docker Images
        run: |
          docker push shaydeecoder/multi-client
          docker push shaydeecoder/multi-nginx
          docker push shaydeecoder/multi-server
          docker push shaydeecoder/multi-worker
