name: Multi-Docker Build, Push and Deploy
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Test Image
        run: docker build -t shaydeecoder/multi-react-test -f ./client/Dockerfile.dev ./client

      - name: Run Tests
        run: docker run -e CI=true shaydeecoder/multi-react-test npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images
        run: |
          docker build -t shaydeecoder/multi-client ./client
          docker build -t shaydeecoder/multi-nginx ./nginx
          docker build -t shaydeecoder/multi-server ./server
          docker build -t shaydeecoder/multi-worker ./worker

      - name: Push Docker Images
        run: |
          docker push shaydeecoder/multi-client
          docker push shaydeecoder/multi-nginx
          docker push shaydeecoder/multi-server
          docker push shaydeecoder/multi-worker

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Option 1: Using beanstalk-deploy Action
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-120036518459
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

      # Option 2: Using AWS EB CLI
      # - name: Install AWS EB CLI
      #   run: pip install awsebcli --upgrade --user

      # - name: Deploy to AWS Elastic Beanstalk
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #     AWS_REGION: us-east-1
      #     EB_APPLICATION: multi-docker
      #     EB_ENVIRONMENT: Multi-docker-env
      #     S3_BUCKET: elasticbeanstalk-us-east-1-120036518459
      #     S3_BUCKET_PATH: docker-multi
      #   run: |
      #     eb init $EB_APPLICATION --platform docker --region $AWS_REGION
      #     eb deploy $EB_ENVIRONMENT
